# Generated by Django 5.1.1 on 2024-09-19 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_billet_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='evenement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.evenement'),
        ),
    ]
