# Generated by Django 5.1.1 on 2024-09-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_billet_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.evenement'),
        ),
    ]
