# Generated by Django 5.1.1 on 2024-09-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_billet_evenement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total',
        ),
    ]
