# Generated by Django 5.1.1 on 2024-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_reservation_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='typebillet',
            name='quantité_billet',
            field=models.IntegerField(default=1),
        ),
    ]
