# Generated by Django 5.1.1 on 2024-09-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_typebillet_quantité_billet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quantite_billets',
            field=models.IntegerField(default=0),
        ),
    ]
