# Generated by Django 5.1.1 on 2024-09-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_quantite_billets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quantite_billets',
        ),
    ]
